name: test runner

on:
  workflow_dispatch:
    inputs:
      args:
        type: string
        default: "--internal --namespace \"New\" --input-files \"alpha\" \"bravo\""
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]

    steps:
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install
      run: |
        dotnet tool install SatorImaging.DotnetTool.StaticImport -g --prerelease

    - name: Env
      run: |
        env

    - name: Tests
      run: |
        touch Editor.meta
        static-import ${{ inputs.args }}
